const mongoose = require('mongoose');

const userSchema = new mongoose.Schema({
  id: { type: String, required: true, unique: true },
  email: { type: String, index: true },
  passwordHash: String,
  name: String,
  username: { type: String, index: true },
  avatar: String,
  level: { type: Number, default: 1 },
  points: { type: Number, default: 0 },
  silverPoints: { type: Number, default: 0 },
  goldenCoins: { type: Number, default: 0 },
  colorBalls: { type: Number, default: 0 },
  magicPoints: { type: Number, default: 0 },
  plusses: { type: Number, default: 0 },
  ap: { type: Number, default: 0 },
  weeklyAp: { type: Number, default: 0 },
  totalAp: { type: Number, default: 0 },
  balance_ap: { type: Number, default: 0 },
  balance_taka: { type: Number, default: 0 },
  reputation_points: { type: Number, default: 0 },
  lastApReset: Number,
  isOnline: { type: Boolean, default: false },
  isPremium: { type: Boolean, default: false },
  isVerified: { type: Boolean, default: false },
  isShadowBanned: { type: Boolean, default: false },
  isBanned: { type: Boolean, default: false },
  pmBan: { type: Boolean, default: false },
  shoutBan: { type: Boolean, default: false },
  chatBan: { type: Boolean, default: false },
  strikes: { type: Number, default: 0 },
  isBot: { type: Boolean, default: false },
  role: { type: String, enum: ['admin', 'moderator', 'user'], default: 'user' },
  user_role: { 
    type: String, 
    enum: [
      'staff', 'admin', 'user', 'trusted_member', 'starter', 'veteran_member', 'premium', 'elite_vip',
      'junior_moderator', 'moderator', 'senior_moderator', 'head_moderator',
      'content_creator', 'event_organizer', 'support_staff', 'system_bot'
    ], 
    default: 'user' 
  },
  badges: [{ type: String }],
  profile_url: String,
  total_rp: { type: Number, default: 0 },
  total_plusses: { type: Number, default: 0 },
  fromCountry: String,
  gender: String,
  education: String,
  work: String,
  currentLocation: String,
  lastActiveTime: Number,
  bio: String,
  customStatus: String,
  ghostMode: { type: Boolean, default: false },
  hiddenVisit: { type: Boolean, default: false },
  userId: { type: Number, index: true },
  sessionToken: String,
  sessionExpiry: Number,
  premiumExpiry: Number,
  elite_active_until: Number,
  premiumPlan: String,
  todayOnlineTime: { type: Number, default: 0 },
  totalOnlineTime: { type: Number, default: 0 },
  lastOnlineDate: String,
  last_archive_created_at: mongoose.Schema.Types.Mixed,
  subscriptionStatus: {
    type: { type: String },
    expiry: Number
  },
  dailyMissions: {
    date: String,
    completed: [String]
  },
  dailyGrabs: mongoose.Schema.Types.Mixed,
  createdAt: { type: Number, default: () => Date.now() },
  lastClaimId: String,
  mutualFriends: Number,
  monsters: [{
    monsterName: String,
    rarity: String,
    element: String,
    count: { type: Number, default: 1 }
  }],
  lastMonsterLogin: Number,
  stamina: { type: Number, default: 100 },
  maxStamina: { type: Number, default: 100 },
  lastStaminaUpdate: { type: Number, default: () => Date.now() },
  goldenBalls: { type: Number, default: 0 },
  dailyStreakCount: { type: Number, default: 0 },
  dailyPoints: { type: Number, default: 0 },
  weeklyPoints: { type: Number, default: 0 },
  dailyGoldenCoins: { type: Number, default: 0 },
  weeklyGoldenCoins: { type: Number, default: 0 },
  dailySilverPoints: { type: Number, default: 0 },
  weeklySilverPoints: { type: Number, default: 0 },
  dailyColorBalls: { type: Number, default: 0 },
  weeklyColorBalls: { type: Number, default: 0 },
  lastDailyReset: String,
  lastWeeklyReset: String,
  favoriteChannels: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Channel' }],
  goldenRevealUntil: { type: Number, default: 0 }
});

module.exports = mongoose.model('User', userSchema);
